src/plugins/foxglove-schemas/generatePages.ts
BEFORE:
- **Loading the page for a message schema with nested schemas** - click the links, get 404s (unnecessary part in the URL)
- **Navigate to that same page from another one** – click the links, consistently get the correct pages
- **Running locally** – click the links, consistently get the correct pages (regardless of page visit history)
AFTER:
- Use absolute paths for links to get rid of unnecessary parts in URLs
=> Fix sometimes incorrect message schema links

docs/3-visualization/4-panels/user-scripts.md
This was a carry-over from a webviz feature that has not existed in Foxglove for a long time (years?). This change removes this incorrect documentation. This removal left one item in the FAQ section so I remove "FAQ" and made the remaining item take its place in the subheaders heirarchy.
=> Remove incorrect user-script FAQ entry for publishing JSON data

docs/0-introduction.md
- Revise intro page for docs (less of a marketing tone; more concrete in terms of platform capabilities)
- Provide lay of the land 
- Outline common workflows, separated by user personas and roles (e.g. roboticists wanting to visualize data vs. dev ops setting up infrastructure)
- Link to existing resources
=> Revise intro page for docs

docs/10-primary-sites/0-introduction.mdx, docs/3-visualization/2-message-schemas/0-introduction.mdx
This documents a limitation of MCAP with data platform (FG-5360) and a workaround for users who would otherwise use an empty MCAP schema. Studio requires that a bare-bones object schema is supplied (if one is supplied at all). As of https://github.com/foxglove/studio/pull/7100, the schema listed here will work.
=> Document workaround for empty schema

docs/3-visualization/8-extensions/0-introduction.mdx, docs/3-visualization/8-extensions/1-api/0-extension-context.mdx
This api call was missing from the documentation. I've also updated the API reference link for @foxglove/studio to link to the typescript file which IMO is a nicer reference link than the folder with the file.
=> Add `registerTopicAliases` to extension context docs

src/plugins/foxglove-schemas/generatePages.ts
Fixed broken links to parent schemas in the message schema documentation.
Fixed by using an absolute instead of relative path.
=> Fix links to parent message schemas

docs/0-introduction.md
- Remove "Getting started" section on the docs intro page (largely a duplicate of the "Workflows" section)
- Fix the streaming docs link
=> More Introduction page revisions

docs/13-webhooks/0-introduction.md
Explains automatic retries to webhook users.
=> add details about automatic retries

docs/10-primary-sites/1-self-hosting/1-manage-data.md, docs/4-importing-data.md
This updates the documentation to support recordings without devices, including describing the purpose of the new "key" parameter and its role.
This includes a restructuring of the self-managed data uploading documentation. The API document updates are in a separate PR (that will make their descriptions public).
=> Updates docs for deviceless data

docs/3-visualization/4-panels/3d.md
Added a troubleshooting section to the docs to explain issue for live connections with asynchronicity between server and client.
Fixes: FG-5229
=> Add troubleshooting section to 3D panel transforms

docs/13-webhooks/0-introduction.md, docs/13-webhooks/1-getting-started.md, docs/13-webhooks/2-security.md
Updates webhooks from being in closed beta to a team or enterprise plan feature.
=> webhooks: update badges to require team or enterprise plan

docs/10-primary-sites/1-self-hosting/2-configure-cloud-credentials.md, docs/11-edge-sites/2-configure-cloud-credentials.mdx
Feedback from a user: our 'secrets' commands didn't include the namespace. This adds it.
=> Add namespace to commands

docs/12-foxglove-agent/2-manage-data.md
This adds a section to the Agent docs on adding recordings. This clarifies the expectations for completeness to avoid transient errors like that described in FG-5890.
=> Document adding files to agent storage

docs/3-visualization/9-shareable-links.md
Added documentation for recordingKey when constructing viz URLs.
With the addition of recordingKey to visualization URLs, this PR updates documentation for said feature.
https://linear.app/foxglove/issue/FG-6390/construct-viz-url-from-key
=> updated recordingKey to docs for viz urls

docs/1-organization-setup/3-okta-sso.mdx, docs/10-primary-sites/0-introduction.mdx, docs/11-edge-sites/0-introduction.mdx, docs/12-foxglove-agent/0-introduction.mdx, docs/12-foxglove-agent/1-installation.mdx, docs/12-foxglove-agent/2-manage-data.mdx, docs/13-webhooks/0-introduction.mdx, docs/13-webhooks/1-getting-started.mdx, docs/13-webhooks/2-security.mdx, docs/3-visualization/3-layouts.mdx, docs/3-visualization/8-extensions/3-publish.mdx, src/components/docs/icons/AccountRequiredHeader.tsx
Updated the docs with better badges to define which features are supported by which plans
With the new pricing plans, we needed to update the docs to reflect the feature/plan matrix. In doing these updates, we changed the badge display to badges per supported plan.
=> show badges for individual plans per feature

docs/6-devices.md, docs/6-devices.mdx
This makes note of a couple of limitations in the new free plan, which is now in effect (https://github.com/foxglove/app/pull/5575).
The new free plan is described by the pricing updates in https://github.com/foxglove/website/pull/1244 with the latest preview at https://website-g73j8cil3.foxglove.party/pricing.
Free plans are also now granted storage and can upload & stream. I don't think this restriction was noted in the documentation before, because we start orgs on the "team trial" plan today.
=> Document some limits for free plans

docs/12-foxglove-agent/1-installation.mdx
- Adds instructions for configure direct bucket upload from Foxglove Agent.
=> agent: include instructions for upload to primary site

docs/2-connecting-to-data/4-frameworks/2-custom.mdx
Let users know that we do not have JSON references support.
=> (chore) note JSON references are unsupported

docs/12-foxglove-agent/1-installation.mdx
This updates the Agent docs, adding a prerequisite for self-managed customers — the agent will need access to the primary inbox bucket.
=> Add self-managed prerequisite

docs/3-visualization/4-panels/image.md
- Sync annotations not supported for video topics
PR that removes capability: https://github.com/foxglove/app/pull/5818
=> Sync annotations not supported for video topics
