foxglove/docs

- docs/3-visualization/8-extensions/0-introduction.mdx
- docs/3-visualization/8-extensions/1-api/0-extension-context.mdx
- docs/3-visualization/8-extensions/1-api/1-panel-api.mdx
- Clean up latest addition to extension docs - clarity and consistency 
- Follow up to #87
> Clean up latest addition to extension docs - clarity and consistency

- docusaurusConfig.ts
- src/plugins/foxglove-schemas/generatePages.ts
This reverts commit d2f2b7f8fb117ac416f61716311a911b1668c00f.
- Reinstated 'Edit this page' links
- To be merged after this repo is made public
> Reinstated 'Edit this page' links

- api-docs/specs/v1.yaml
> Update API docs

- docs/3-visualization/4-panels/image.md
- Use consistent formatting for Annex B 
cc: @snosenzo
> Use consistent formatting for Annex B

- src/plugins/foxglove-schemas/generatePages.ts
- Fix font size and styling of message schema page headers
> Fix styling of message schema page headers

- docs/0-introduction.md
- Fix formatting of new 'Visualize' list item on Intro page
> Fix formatting of new 'Visualize' list item on Intro page

- docs/0-introduction.md
- Clean up intro page based on feedback and edits
> Clean up intro page based on feedback and edits

- docs/12-foxglove-agent/2-manage-data.md
Adds some extra information about deleting files on a device.
> foxglove-agent: add note regard deleting files

- docs/12-foxglove-agent/0-introduction.md
Update agent docs to say Team or Enrerprise required
> Update agent plan notice

- docusaurusConfig.ts
- N/A
- Throw error if markdown contains bad link (FG-6068)
> Throw error if markdown contains bad link

- docs/13-webhooks/1-concepts.md
- docusaurusConfig.ts
- Fix prod URL in docusaurus project to catch broken links
Final commit in this PR fixes the above errors.
> Fix prod URL in docusaurus project to catch broken links

- api-docs/specs/v1.yaml
> Bump API docs to cecc4eb

- .github/workflows/auto-approve.yml
- .vscode/settings.json
N/A
Automatically approve @foxglovebot PRs.
> Auto-approve @foxglovebot PRs

- api-docs/specs/v1.yaml
> Bump API docs to `ac5cebd`

- api-docs/specs/v1.yaml
> Bump API docs to `1e6975b`

- docs/10-primary-sites/0-introduction.mdx
- docs/10-primary-sites/1-self-hosting/0-installation.md
- docs/10-primary-sites/1-self-hosting/2-configure-cloud-credentials.md
- docs/11-edge-sites/1-installation.md
- docs/11-edge-sites/2-configure-cloud-credentials.mdx
This adds documentation for S3-compatible primary site setups, particularly MinIO.
> Document s3-compatible (MinIO) Primary Site

- api-docs/specs/v1.yaml
> Bump API docs to `5c7d307`

- api-docs/specs/v1.yaml
> Bump API docs to `faabb82`

- docs/14-cli.md
> Make download executable

- api-docs/specs/v1.yaml
> Bump API docs to `ae402f9`

- api-docs/specs/v1.yaml
> Bump API docs to `48e790d`

- docs/10-primary-sites/1-self-hosting/0-installation.md
Created made completed yaml examples for each storage type
> Primary site install YAML examples

- docs/10-primary-sites/1-self-hosting/2-configure-cloud-credentials.md
Change docs to be clear and easy to follow.
See linear
> Update cloud credientials instructions for GCP.

- api-docs/specs/v1.yaml
> Bump API docs to `246fe31`

- api-docs/specs/v1.yaml
> Bump API docs to `525fa4e`

- api-docs/specs/v1.yaml
> Bump API docs to `3c89367`

- api-docs/specs/v1.yaml
> Bump API docs to `eb4bdbf`

- docs/12-foxglove-agent/2-manage-data.mdx
- documents the `WATCH_AUTO_IMPORT_PATTERN` feature recently added to foxglove agent.
> agent: document auto_import pattern

- api-docs/specs/v1.yaml
> Bump API docs to `2477036`

- .github/workflows/ci.yml
None
Allows the site to be rebuilt on an automated trigger.
> Add repository_dispatch trigger to CI

- api-docs/specs/v1.yaml
> Bump API docs to `5084da3`

- docs/1-organization-setup/3-okta-sso.mdx
- docs/13-webhooks/1-getting-started.mdx
- docs/2-connecting-to-data/1-live-data.md
- docs/2-connecting-to-data/4-frameworks/3-mcap.mdx
- docs/3-visualization/0-introduction.md
- docs/3-visualization/8-extensions/3-publish.mdx
- src/components/docs/connecting-to-data/LocalDataDirections.tsx
Updating doc urls & screenshots
> replaced studio and console urls with app

- api-docs/specs/v1.yaml
> Bump API docs to `eec5242`

- api-docs/specs/ref/components/responses.yaml
- api-docs/specs/v1.yaml
> Bump API docs to `179f99e`

- api-docs/specs/v1.yaml
> Bump API docs to `a949d29`

- api-docs/specs/v1.yaml
> Bump API docs to `bca7b24`

- api-docs/specs/v1.yaml
> Bump API docs to `b53203f`

- api-docs/specs/v1.yaml
> Bump API docs to `dcd8934`

- docs/2-connecting-to-data/4-ros-foxglove-bridge.md
None
Updates the foxglove-bridge documentation to match the documentation found at https://github.com/foxglove/ros-foxglove-bridge
> update foxglove-bridge documentation

- api-docs/specs/ref/components/responses.yaml
- api-docs/specs/v1.yaml
> Bump API docs to `217ca3e`

- docs/3-visualization/4-panels/publish.md
None
Update publishing panel docs
> Update publishing panel docs
